version: '3.8'

services:
  # Microservice for collections (test version)
  collection_test:
    build:
      context: .
      dockerfile: ./collection/Dockerfile
    container_name: collection_test
    ports:  # Binding della porta
      - "5002:5002"  # Espone la porta 5002 del container sulla porta 5002 dell'host
    environment:
      - FLASK_ENV=testing
      - DB_HOST=collection_db
      - DB_PORT=3306
      - DB_NAME=${DB_COLLECTION_NAME}
      - DB_USER=${DB_COLLECTION_USER}
    secrets:
      - db_collection_password
      - collection_cert
      - collection_key
      - mysql_ca_cert
      - collection_db_cert
      - collection_db_key
    depends_on:
      collection_db:
        condition: service_healthy  # Ensure the database starts before the service

  # MySQL for the collection microservice
  collection_db:
    image: mysql:8
    container_name: collection_db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${DB_COLLECTION_NAME}
      - MYSQL_USER=${DB_COLLECTION_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_collection_password
    command: --ssl-ca=/run/secrets/mysql_ca_cert --ssl-cert=/run/secrets/collection_db_cert --ssl-key=/run/secrets/collection_db_key
    secrets:
      - db_collection_password
      - mysql_ca_cert
      - collection_db_cert
      - collection_db_key
      - db_root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - test_collection_db_data:/var/lib/mysql
      - ./collection/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./collection/db/images:/collection_db/items_images

volumes:
  test_collection_db_data:

secrets:
  # DB Password secrets
  db_collection_password:
    file: ./secrets/collection/db_password.txt
  db_root_password:
    file: ./secrets/mysql/db_password.txt

  # Microservices certificates
  collection_cert:
    file: ./secrets/collection/cert.pem
  collection_key:
    file: ./secrets/collection/key.pem

  mysql_ca_cert:
    file: ./secrets/mysql/mysql_ca_cert.pem
  collection_db_cert:
    file: ./secrets/collection/db_cert.pem
  collection_db_key:
    file: ./secrets/collection/db_key.pem