version: '3.8'

services:
  # Microservice for payment (test version)
  payment_test:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: payment_test
    ports:
      - "5007:5007"  # Espone la porta 5007 del container sulla stessa porta dell'host
    environment:
      - FLASK_ENV=testing
      - DB_HOST=payment_db
      - DB_PORT=3306
      - DB_NAME=${DB_PAYMENT_NAME}
      - DB_USER=${DB_PAYMENT_USER}
      - AES_SECRET_KEY_FILE=/run/secrets/aes_secret_key
    secrets:
      - db_payment_password
      - payment_cert
      - payment_key
      - mysql_ca_cert
      - payment_db_cert
      - payment_db_key
      - aes_secret_key
    depends_on:
      payment_db:
        condition: service_healthy  # Garantisce che il DB sia attivo prima di avviare il servizio

  # MySQL for the payment microservice (test database)
  payment_db:
    image: mysql:8
    container_name: payment_db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${DB_PAYMENT_NAME}
      - MYSQL_USER=${DB_PAYMENT_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_payment_password
    command: --ssl-ca=/run/secrets/mysql_ca_cert --ssl-cert=/run/secrets/payment_db_cert --ssl-key=/run/secrets/payment_db_key
    secrets:
      - db_payment_password
      - mysql_ca_cert
      - payment_db_cert
      - payment_db_key
      - db_root_password
    ports:
      - "3306:3306"  # Esponi la porta del DB per connetterti dal tuo host
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - test_payment_db_data:/var/lib/mysql
      - ./payment/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  test_payment_db_data:

secrets:
  # DB Password secrets
  db_payment_password:
    file: ./secrets/payment/db_password.txt
  db_root_password:
    file: ./secrets/mysql/db_password.txt

  # Microservices certificates
  payment_cert:
    file: ./secrets/payment/cert.pem
  payment_key:
    file: ./secrets/payment/key.pem

  mysql_ca_cert:
    file: ./secrets/mysql/mysql_ca_cert.pem
  payment_db_cert:
    file: ./secrets/payment/db_cert.pem
  payment_db_key:
    file: ./secrets/payment/db_key.pem

  # AES secret key for payment
  aes_secret_key:
    file: ./secrets/payment/aes_secret_key.txt
