version: '3.8'

services:
  auth_test:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    container_name: auth_test
    ports:  
      - "5011:5011"  
    environment:
      - FLASK_ENV=testing
    secrets:
      - auth_cert
      - auth_key

secrets:
  auth_cert:
    file: ./secrets/auth/cert.pem
  auth_key:
    file: ./secrets/auth/key.pem


