version: '3.8'

services:
  # Microservice for currency (test version)
  currency_test:
    build:
      context: .
      dockerfile: ./currency/Dockerfile
    container_name: currency_test
    ports:  # Binding della porta
      - "5005:5005"  # Espone la porta 5005 del container sulla porta 5005 dell'host
    environment:
      - FLASK_ENV=testing
      - DB_HOST=currency_db
      - DB_PORT=3306
      - DB_NAME=${DB_CURRENCY_NAME}
      - DB_USER=${DB_CURRENCY_USER}
    secrets:
      - db_currency_password
      - currency_cert
      - currency_key
      - mysql_ca_cert
      - currency_db_cert
      - currency_db_key
    depends_on:
      currency_db:
        condition: service_healthy  # Ensure the database starts before the service

  # MySQL for the currency microservice
  currency_db:
    image: mysql:8
    container_name: currency_db
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=${DB_CURRENCY_NAME}
      - MYSQL_USER=${DB_CURRENCY_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/db_currency_password
    command: --ssl-ca=/run/secrets/mysql_ca_cert --ssl-cert=/run/secrets/currency_db_cert --ssl-key=/run/secrets/currency_db_key
    secrets:
      - db_currency_password
      - mysql_ca_cert
      - currency_db_cert
      - currency_db_key
      - db_root_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - test_currency_db_data:/var/lib/mysql
      - ./currency/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  test_currency_db_data:
    
secrets:
  # DB Password secrets
  db_currency_password:
    file: ./secrets/currency/db_password.txt
  db_root_password:
    file: ./secrets/mysql/db_password.txt

  # Microservices certificates
  currency_cert:
    file: ./secrets/currency/cert.pem
  currency_key:
    file: ./secrets/currency/key.pem

  mysql_ca_cert:
    file: ./secrets/mysql/mysql_ca_cert.pem
  currency_db_cert:
    file: ./secrets/currency/db_cert.pem
  currency_db_key:
    file: ./secrets/currency/db_key.pem
