# Usa l'immagine Nginx ufficiale
FROM nginx:alpine

# Copia il file HTML nella posizione predefinita di Nginx
COPY ./client.html /usr/share/nginx/html/index.html

# Esponi la porta 80 per il servizio web
EXPOSE 80
