name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Step per clonare il repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step per configurare Node.js (necessario per installare Newman)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Step per installare Newman
    - name: Install Newman
      run: npm install -g newman

    # Step per configurare Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step per installare Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Step per build del servizio Market
    - name: Build Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml build

    # Step per run del servizio Market e eseguire i test
    - name: Run and Test Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml up -d

    - name: Wait for Market Service
      run: |
        echo "Waiting for Market Service to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:5004 > /dev/null; then
            echo "Market Service is up!"
            break
          fi
          echo "Service not ready, retrying in 5 seconds..."
          sleep 5
        done

    - name: Run Market Tests
      run: |
        newman run ./docs/tests/Market_Test.postman_collection.json

    - name: Check Market Logs
      run: docker logs market_test

    # Step per down del servizio Market
    - name: Tear Down Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml down -v

