name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Step per clonare il repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step per configurare Node.js (necessario per installare Newman)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Step per installare Newman
    - name: Install Newman
      run: npm install -g newman

    # Step per configurare Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step per installare Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Step per build del servizio Account
    - name: Build Account Service
      run: |
        docker-compose -f ./src/docker-compose.account.yml build

    # Step per run del servizio Account e eseguire i test
    - name: Run and Test Account Service
      run: |
        docker-compose -f ./src/docker-compose.account.yml up -d
        newman run ./docs/tests/Account_Test.postman_collection.json --insecure

    # Step per down del servizio Account
    - name: Tear Down Account Service
      run: |
        docker-compose -f ./src/docker-compose.account.yml down -v

    # Step per build del servizio Collection
    - name: Build Collection Service
      run: |
        docker-compose -f ./src/docker-compose.collection.yml build

    # Step per run del servizio Collection e eseguire i test
    - name: Run and Test Collection Service
      run: |
        docker-compose -f ./src/docker-compose.collection.yml up -d
        newman run ./docs/tests/Collection_Test.postman_collection.json --insecure

    # Step per down del servizio Collection
    - name: Tear Down Collection Service
      run: |
        docker-compose -f ./src/docker-compose.collection.yml down -v

    # Step per build del servizio Currency
    - name: Build Currency Service
      run: |
        docker-compose -f ./src/docker-compose.currency.yml build

    # Step per run del servizio Currency e eseguire i test
    - name: Run and Test Currency Service
      run: |
        docker-compose -f ./src/docker-compose.currency.yml up -d
        newman run ./docs/tests/Currency_Test.postman_collection.json --insecure

    # Step per down del servizio Currency
    - name: Tear Down Currency Service
      run: |
        docker-compose -f ./src/docker-compose.currency.yml down -v

        # Step per build del servizio Market
    - name: Build Market Service
      run: |
       docker-compose -f ./src/docker-compose.market.yml build

    # Step per run del servizio Market e eseguire i test
    - name: Run and Test Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml up -d
        newman run ./docs/tests/Market_Test.postman_collection.json --insecure

    # Step per down del servizio Market
    - name: Tear Down Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml down -v

    # Step per build del servizio Payment
    - name: Build Payment Service
      run: |
        docker-compose -f ./src/docker-compose.payment.yml build

    # Step per run del servizio Payment e eseguire i test
    - name: Run and Test Payment Service
      run: |
        docker-compose -f ./src/docker-compose.payment.yml up -d
        newman run ./docs/tests/Payment_Test.postman_collection.json --insecure

    # Step per down del servizio Payment
    - name: Tear Down Payment Service
      run: |
        docker-compose -f ./src/docker-compose.payment.yml down -v

    # Step per build dell'applicazione
    - name: Build Docker Compose
      run: |
        docker-compose -f ./src/docker-compose.yml build

    # Step per run dell'applicazione e eseguire i test
    - name: Run and Test Docker Compose
      run: |
        docker-compose -f ./src/docker-compose.yml up -d
        newman run ./docs/tests/Integration_test.postman_collection.json --insecure

    # Step per down dell'applicazione
    - name: Tear Down Docker Compose
      run: |
        docker-compose -f ./src/docker-compose.yml down -v
