name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  market_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml up -d

    - name: Wait for Market Service
      run: |
        echo "Waiting for Market Service to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:5004 > /dev/null; then
            echo "Market Service is up!"
            break
          fi
          echo "Service not ready, retrying in 5 seconds..."
          sleep 5
        done

    - name: Run Market Tests
      run: |
        newman run ./docs/tests/Market_Test.postman_collection.json --env-var baseUrl=http://market_test:5004

    - name: Check Market Logs
      run: docker logs market_test

    - name: Tear Down Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml down -v

    # Step per down del servizio Payment
    - name: Tear Down Payment Service
      run: |
        docker-compose -f ./src/docker-compose.payment.yml down -v

    # Step per build del servizio Market
    - name: Build Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml build

    # Step per run del servizio Market e eseguire i test
    - name: Run and Test Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml up -d
        newman run ./docs/tests/Market_Test.postman_collection.json

    # Step per down del servizio Market
    - name: Tear Down Market Service
      run: |
        docker-compose -f ./src/docker-compose.market.yml down -v

