name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Step per clonare il repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step per configurare Node.js (necessario per installare Newman)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Step per installare Newman
    - name: Install Newman
      run: npm install -g newman

    # Step per configurare Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step per installare Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Step per eseguire i test del servizio Account (uso del percorso assoluto)
    - name: Build and Test Account Service
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.account.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Account_Test.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.account.yml down -v

    # Step per eseguire i test del servizio Collection
    - name: Build and Test Collection Service
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.collection.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Collection_Test.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.collection.yml down -v

    # Step per eseguire i test del servizio Currency
    - name: Build and Test Currency Service
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.currency.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Currency_Test.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.currency.yml down -v

    # Step per eseguire i test del servizio Market
    - name: Build and Test Market Service
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.market.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Market_Test.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.market.yml down -v

    # Step per eseguire i test del servizio Payment
    - name: Build and Test Payment Service
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.payment.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Payment.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.payment.yml down -v

    # Step finale per eseguire i test di integrazione
    - name: Run Integration Tests
      run: |
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.yml up --build -d
        newman run /home/runner/work/Ase_project24-25/docs/tests/Integration_test.postman_collection.json
        docker-compose -f /home/runner/work/Ase_project24-25/src/docker-compose.yml down -v
