name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    # Step per clonare il repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step per configurare Node.js (necessario per installare Newman)
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    # Step per installare Newman
    - name: Install Newman
      run: npm install -g newman

    # Step per configurare Docker Buildx
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    # Step per installare Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Print current working directory
      run: |
        echo "Current working directory:"
        pwd
        
    # Step per buildare il Docker Compose degli integration tests
    - name: build integration tests compose
      run:  |
        docker-compose -f ./src/docker-compose.yml build
        docker-compose -f ./src/docker-compose.yml up -d

    # Step finale per eseguire i test di integrazione
    - name: Run Integration Tests
      run: |
        sleep 5
        newman run ./docs/tests/Integration_test.postman_collection.json
        docker-compose -f ./src/docker-compose.yml down -v
